### ISSUE TITLE
Entities within HTML macros

### ISSUE THREAD

**Issue by plinfut** [turnermm/TextInsert#14]
I'm trying to make a macro to explain the use of commands and the common syntax for required parameters is &lt;parameter&gt;. But if I include &lt;parameter&gt; or `&lt;parameter&gt;` in the macro replacement, it is converted to regular &lt;parameter&gt; on insert and hidden as an unknown HTML tag.

**Comment by turnermm** [comment]
This occurs only if you use the HTML replacement pattern:  macro_HTML.  Without the _HTML suffix, the html entities are escaped.  See this example based on your requirements:
    http://mturner.org/devel/playground/entities#textinsert

**Comment by plinfut** [comment]
Thank you for your quick reply. I understand that, but without the _HTML suffix I am unable to add line breaks. Is there any way to use entities and HTML (or at the very least line breaks) together?

**Comment by turnermm** [comment]
Sorry, I realized that I hadn't really answered  your question and planned to get back to you.

 There is a way to do this with HTML macros.  But there is a small sacrifice.  In your macro definition, leave a single space after the first and in front of the second angle bracket: `< %1 >`.  The `%1` is a place holder, as described on the textinsert plugin page.   You can substitute any term(s) required for the `%1`.  The only drawback is that the spaces will appear in the final result: `< parameter >`

 Please refer again to the above cited page: http://mturner.org/devel/playground/entities#textinsert.  It includes an example of this usage.

**Comment by plinfut** [comment]
Thank you. That is a reasonable solution. Feel free to close this issue as solved. :)
