### ISSUE TITLE
Context of macro variables

### ISSUE THREAD

**Issue by moz0817** [turnermm/TextInsert#18]
If I use a macro with a variable (i.e.` #@ID@#` ) in the sidebar, the value is always taken from the sidebar.
Is it wanted like that? For me a dynamic value from the **current page** would be more useful.

**Comment by turnermm** [comment]
The sidebar is a wiki page, so the ID is the id of that page.

**Comment by turnermm** [comment]
I've added a fix for this case.  See the descitpion on the plugin page and download the update.

https://www.dokuwiki.org/plugin:textinsert#standard_namespace_macros
