### ISSUE TITLE
Buttons don't work 

### ISSUE THREAD

**Issue by thojo0** [turnermm/TextInsert#23]
When I click on add or delete the information Text gets invisible and nothing happens
I'm using DokuWiki Release 2018-04-22a "Greebo"

**Comment by turnermm** [comment]
I can't reproduce this.  If you aren't using the dokuwiki template, switch over to it and see if the problem is still there.

**Comment by thojo0** [comment]
Ok thanks. It works with the normal dokuwiki tamplate.
Is it possible for you to make it is also working with other tamplates like sprintdoc?

**Comment by turnermm** [comment]
It works with other templates.  I just tested it using 6 templates of different types from different periods and it works in all of them.  The only one it doesn't work in is sprintdoc.

**Comment by thojo0** [comment]
OK
Maybe you can add this but thanks for the short answer.
