### ISSUE TITLE
macro not substituted in http link

### ISSUE THREAD

**Issue by marcbavay** [turnermm/TextInsert#25]
Hi,
I created a macro srvdoc which is correcly substituted using #@srvdoc@#
I hoped to store in this macro the base name of a server address because it can change depending where the wiki is located.
But I cannot get the macro to be substituted inside the https link, it shows up like this :
https://**#@srvdoc@#**/gems/mco-k6/n4/xpOpenDocAgent.xsp?ref=121759/DID.238&get=file
Is it there a way around this ?
Thank you for your answer
PS  : I am using 2014-09-29b "Hrun" and the oldest compatible declared on your wiki page is 2014-05-05a "Ponder Stibbons", could this be the problem ?

**Comment by turnermm** [comment]
Try using the parameter interpolation form:
 https://www.dokuwiki.org/plugin:textinsert#parameter_interpolation.
That might be a big inconvenient.

Or you might store your addresses as entities:
 https://www.dokuwiki.org/plugin:textinsert#entity_inclusions

**Comment by turnermm** [comment]
Here is how you can use parameters:
macro name:  `server1_HTML`

macro definition:
`<a href='https://%1/gems/mco-k6/n4/xpOpenDocAgent.xsp?ref=121759/DID.238&get=file' >%2</a>`

The macro:
`#@server_HTML~primary.org,document1.docx~@#`

The result:
https://primary.org/gems/mco-k6/n4/xpOpenDocAgent.xsp?ref=121759/DID.238&amp;get=file

**Comment by marcbavay** [comment]
Thank you very much !
I tried with entities, I could display the right url, mais could not make a link out of it
Parameters is the right mechanism for me, I just had to tweak the arguments, it is working great
Mucho thanks again for that really nice plugin
