### ISSUE TITLE
Macros inside the File or Code tag

### ISSUE THREAD

**Issue by EvgeniyDoctor** [turnermm/TextInsert#29]
I want to use a macros inside the `file` or `code` tag, but it does not work.
Here is my macros DC:
```
dc(){ bash... }; dc "%1"
```
If i just write `#@DC~data~@#` it will work, but if i wrap it with `code` tag like this:
```
<code bash>
#@DC~data~@#
</code>
```
i see `#@DC~data~@#` as is.

And i tried already put html tags to DC_HTML to simulate the `code` tag (`<pre></pre>`). But i think this is a bad idea and syntax highlighting is not working with this.

So, how can i achieve this?

**Comment by turnermm** [comment]
The function of the code tag is to output the text literally. All markup is output as is.
